# This workflow will build and test a .NET project.
# Web server is in the folder backend.
# Tests are in the folder testBackend

name: .NET

on:
  push:
    branches: [ "master", "test/github-actions" ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
      
  pull_request:
    branches: [ "master", "test/github-actions" ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore

  workflow_dispatch:
    
jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        cache: true
        cache-dependency-path: "./backend/WebServer"
  
    - name: Restore dependencies
      run: |
        cd ./backend/WebServer
        dotnet restore --locked-mode
        cd ../../testBackend
        dotnet restore --locked-mode
          
    - name: Build
      working-directory: ./backend/WebServer
      run: dotnet build --no-restore
      
    - name: Test
      working-directory: ./testBackend
      run: dotnet test --no-build --verbosity normal

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./backend/WebServer
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/langlearner:latest, ${{ secrets.DOCKERHUB_USERNAME }}/langlearner:${{ github.run_number }}
